In [1]:
import gym
import numpy as np

In [2]:
env = gym.make('CartPole-v0')
env.reset()

array([-0.00256854,  0.04172676, -0.01354802,  0.04520957])

In [13]:
env.action_space

Discrete(2)

In [17]:
for i in range(5):
    print(  env.action_space.sample()  )

1
0
0
0
0


In [156]:
env.reset()

array([ 0.0419905 , -0.02537445,  0.02612332,  0.01725738])

In [157]:
env.env.state

array([ 0.0419905 , -0.02537445,  0.02612332,  0.01725738])

In [136]:
env.step(env.action_space.sample())
env.render()

True

In [158]:
env.close()

In [166]:
import gym
env = gym.make('CartPole-v0')
print(env.action_space)
#> Discrete(2)
print(env.observation_space)
#> Box(4,)

Discrete(2)
Box(4,)


In [167]:
print(env.observation_space.high)
print(env.observation_space.low)

[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


In [2]:
from gym import spaces
space = spaces.Discrete(8) # Set with 8 elements {0, 1, 2, ..., 7}
x = space.sample()
assert space.contains(x)
assert space.n == 8

In [15]:
import gym
env = gym.make('CartPole-v0')
#env = gym.wrappers.Monitor(env, "./vid", \
#        video_callable=lambda episode_id: True, force=True)
env = gym.wrappers.Monitor(env, "./vid", force=True)

In [16]:
for i_episode in range(3):
    observation = env.reset()
    action = 0
    for t in range(200):
        env.render()
        #print(observation)
        #action = env.action_space.sample()
        action+=1
        observation, reward, done, info = env.step(action%2)
        
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

Episode finished after 26 timesteps
Episode finished after 50 timesteps
Episode finished after 45 timesteps


In [106]:

env = gym.make('LunarLander-v2')
env = gym.wrappers.Monitor(env, "./vid", force=True)

for i_episode in range(1):
    observation = env.reset()
    for t in range(100):
        env.render()
        #print(observation)
        #action = env.action_space.sample()
        #action=0
        
        observation, reward, done, info = env.step(action)
        
        if t%4!=0:
            action = int(  (observation[2]>=0)*2 + 1   )
        else:
            action = 2
        #if observation[2]>=0:
        #    action = 1
        #elif observation[2]<0:
        
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()

In [173]:
env.action_space

Discrete(4)

In [55]:
observation

array([-1.001602  ,  0.350554  , -1.6879733 , -0.7959021 ,  0.5877689 ,
        0.11282446,  0.        ,  0.        ], dtype=float32)